using UnityEngine;

public class Bala : MonoBehaviour
{
    public float da単o = 2.0f; // Da単o que la bala inflige

    private void OnCollisionEnter(Collision collision)
    {
        // Verifica si la bala impacta con un objeto que tiene el componente LogicaBarraVida
        LogicaBarraVida barraVida = collision.gameObject.GetComponent<LogicaBarraVida>();
        if (barraVida != null && collision.gameObject.CompareTag("Enemigo"))
        {
            Debug.Log("Haciendo da単o a enemigo");
            // Reduce la vida del objeto impactado
            barraVida.vidaActual -= da単o;
        }

        // Destruye la bala tras el impacto
        Destroy(gameObject);
    }
}
